export type PageKey =
  | "dashboard"
  | "clients"
  | "commandes"
  | "paiements"
  | "factures"
  | "mesures"
  | "parametres"
  | "matieres"
  | "ventes"
  | "employes"
  | "prestations_types"
  | "prestations_realisees"
  | "emprunts"
  | "depenses"
  | "sorties_tenues"
  | "bilan_financier"
  | "etats_financiers"
  | "entrees_stock"
  | "sorties_stock"
  | "utilisateurs"
  | "clients_mesures"
  | "journal_caisse"
  | "stock_global" // ✅ AJOUT
  | "salaires"
  | "bulletin_salaire"
  | "salaires_historique";